### ISSUE TITLE
How can I convert this to Server Side Rendering

### ISSUE THREAD

**Issue by robertfyffe** [blivesta/wp-react-spa-boilerplate#1]
I wanted to say thanks for providing this great repository. The technologies used are impressive and I have been considering using this structure on an upcoming project. 

My only concern would be disadvantages of using this setup when focused on SEO. Is it possible to provide a version of this where the content is rendered on the server? I have tried this myself but just not able to get everything to play nice together.

**Comment by blivesta** [comment]
I’m not a SEO expert, but most search engines are indexed in SPA as well. However, there seems to be a search engine which can not crawl it.

[SEO vs. React: Web Crawlers are Smarter Than You Think](https://medium.freecodecamp.com/seo-vs-react-is-it-neccessary-to-render-react-pages-in-the-backend-74ce5015c0c9#.imwjstrlx)

As for SSR, I think that it is difficult because the configuration of the back-end is different from the current repository.
In case of emphasizing SEO on a small web site, a static site generator based on React may be good.

https://github.com/gatsbyjs/gatsby
https://github.com/markdalgleish/static-site-generator-webpack-plugin

https://github.com/kriasoft/react-static-boilerplate
https://github.com/koba04/react-server-side-rendering-sample

Thanks.
